### ISSUE TITLE
can not running

### ISSUE THREAD

**Issue by bhzhu203** [georgebakas/Crypto_Prediction#1]
python main_training.py         
2021-03-18 10:50:29.521475: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /stow/lib32/
2021-03-18 10:50:29.521525: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /stow/lib32/
2021-03-18 10:50:29.521532: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
unix           float64
date            object
symbol          object
open           float64
high           float64
low            float64
close          float64
Volume BTC     float64
Volume USDT    float64
tradecount     float64
dtype: object

*** DF ***
Traceback (most recent call last):
  File "main_training.py", line 37, in <module>
    df_copy['dt_correct'] = df.unix.apply(lambda x: change_timestamp(x))
  File "/home/bhzhu/source/Crypto_Prediction/test1/lib/python2.7/site-packages/pandas/core/series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "main_training.py", line 37, in <lambda>
    df_copy['dt_correct'] = df.unix.apply(lambda x: change_timestamp(x))
  File "main_training.py", line 32, in change_timestamp
    return (datetime.datetime.utcfromtimestamp(ts)).strftime('%Y-%m-%d %H:%M:%S')
ValueError: year is out of range

**Comment by georgebakas** [comment]
What is the version of Python and TensorFlow that you are running?

**Comment by bhzhu203** [comment]
Sorry when use python3 erverything is fine . And the python2 doesnot support your program
